### PR TITLE
Pbi 198: Populate price payload with uom

### PR DESCRIPTION
**Pull request by bryannaufal**
## Describe your changes
- Implemented getUOMByID functionality
- Updated the price payload to include UOM information.
- Added the quantity field to the price response

## Issue ticket number and link
https://linear.app/adudu/issue/ADU-197/enrich-price-payload-with-the-respective-uom

image

### CODE REVIEW

**Review by edutjie — APPROVED** [review]
great job! LGTM

**Comment by valeelim** [comment]
astounding work 🎉

**Comment by ferryhieronimus** [comment]
> On another note, it seems that these pull requests that populates the existing payload is not backward compatible. Since our schema changes, the front end would have to change their schemas as well.
> 
> Syncing the front end and back end during deployment in real life scenario a problem. Deploying the backend would cause the front end to break no matter what happens.
> 
> I think for future improvements, we could utilize gRPC to maintain the backward compatibility.

Woah, since you mentioned gRPC, I’d like to know the pros and cons of using it. Could you also provide a brief description of gRPC? I’ve heard a lot about it but haven’t had a chance to implement it yet

**Comment by ferryhieronimus** [comment]
> gRPC addresses backward compatibility issues by leveraging protocol buffers (protobuf) for defining data schemas. Protobuf allows schema changes by enabling developers to add new fields to a message without breaking existing implementations. When the gRPC server adds the data schema with additional fields, older clients simply ignore the unknown fields, ensuring compatibility. Similarly, new clients can safely handle older messages without expecting fields that might not exist.
> 
> Hence the client implementation would still work as intended

Does implementing it require breaking changes or a lot of modifications? Also, can we use both HTTP and gRPC together?

**Pull request merged**
