### PR TITLE
PBI-124-125-126-127 : Fix Query Authentication Backend

### PR DESCRIPTION
**Pull request by bryannaufal**
## Describe your changes
Update Find Account by Email Query

## Issue ticket number and link
ADU-124: https://linear.app/adudu/issue/ADU-124/authentication-accessor
ADU-125: https://linear.app/adudu/issue/ADU-125/authentication-service
ADU-126: [https://linear.app/adudu/issue/ADU-126/[unit-test]-authentication-service](https://linear.app/adudu/issue/ADU-126/%5Bunit-test%5D-authentication-service)
ADU-127: [https://linear.app/adudu/issue/ADU-127/[unit-test]-authentication-accessor](https://linear.app/adudu/issue/ADU-127/%5Bunit-test%5D-authentication-accessor)

### CODE REVIEW

**Comment by valenciusap17** [comment]
What bug does this PR fix? Can you give a brief explanation?

**Comment by bryannaufal** [comment]
The parameter is passed incorrectly to the query, which will cause an error.

**Comment by valeelim** [comment]
LGTM, have you tested it?

**Comment by bryannaufal** [comment]
I already tested it

**Pull request merged**
